id: I0DF87605
legacy_id: P001657
ocr_import_info:
  bdrc_scan_id: W28897
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T14:41:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:15:48.281763+00:00'
last_modified: 2022-09-02 17:17:40.660698
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28897
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28897
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པ་རབ་རྒྱས།
  author: བྲག་དཀར་སྔགས་རམས་པ་བློ་བཟང་བསྟན་པ་རབ་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.7371981792723623
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I4821:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4821
      total_pages: 712
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4821.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7439642229731138
    legacy_id: v001
  I4822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4822
      total_pages: 404
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4822.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7249066528929015
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
